name: Update expo
on: [push]

jobs:
  easUpdate:
    name: Update EAS
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'github actions - gen update')
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: xOhedZB0gXh_9ov40Uzt0gd1wOGIwhu6plESS84l
      - name: Install dependencies
        run: yarn
      - name: Update on EAS
        id: step_one
        run: eas update --channel preview --message "teste1" --non-interactive

      - name: Set the value
        id: step_two
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"

      - name: Use the value
        id: step_three
        run: |
          printf '%s\n' "$action_state" # This will output 'yellow'

      - name: Use the value 2
        id: step_four
        run: |
          printf '%s\n' "$steps.step_one" # This will output 'step_one'

      - name: Set the value 3
        id: step_five
        run: |
          echo "eas_resp=$steps.step_one" >> "$GITHUB_ENV"

      - name: Use the value 3
        id: step_six
        run: |
          printf '%s\n' "$eas_resp" # This will output 'eas_resp'
  # setFirebase:
  #   name: set firebase
  #   runs-on: ubuntu-latest
  #   if: ${{ always() }}
  #   needs: [easUpdate]
      # steps:
      #  - name: Update Firestore
      #   run: firebase-tools xxx
        
