name: Update expo
on: [push]

jobs:
  easUpdate:
    name: Update EAS
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'github actions - gen update')
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: xOhedZB0gXh_9ov40Uzt0gd1wOGIwhu6plESS84l
      - name: Install dependencies
        run: yarn
      - name: Update on EAS
        run: |
          eas update --channel preview --message "teste1" --non-interactive
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
      - name: Escreva
        run: echo "escreva algo e mostre -> '${ github.event }'"
  # setFirebase:
  #   name: set firebase
  #   runs-on: ubuntu-latest
  #   if: ${{ always() }}
  #   needs: [easUpdate]
      # steps:
      #  - name: Update Firestore
      #   run: firebase-tools xxx
        
