name: Update expo
on: [push]

jobs:
  easUpdate:
    name: Update EAS
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.response }}
    if: contains(github.event.head_commit.message, 'github actions - gen update')
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: xOhedZB0gXh_9ov40Uzt0gd1wOGIwhu6plESS84l
      - name: Install dependencies
        run: yarn

      - id: step 1
        run: eas update --channel preview --message "teste1" --non-interactive

      - name: "teste1"
        run: echo "response=helloWorld" >> $GITHUB_OUTPUT

      - name: Use the value
        id: step_two
        run: |
          printf '%s\n' "$response"



      # - name: Set the value
      #   id: step_one
      #   run: |
      #     echo "action_state=yellow" >> "$GITHUB_ENV"
      # - name: Use the value
      #   id: step_two
      #   run: |
      #     printf '%s\n' "$action_state" # This will output 'yellow'
      
  # setFirebase:
  #   name: set firebase
  #   runs-on: ubuntu-latest
  #   if: ${{ always() }}
  #   needs: [easUpdate]
      # steps:
      #  - name: Update Firestore
      #   run: firebase-tools xxx
        
